-- Seed ~50 catégories marketplace (idempotent via slug unique)
insert into categories (slug, name, icon) values
  ('marketing', 'Marketing', '📣'),
  ('ventes', 'Ventes', '💼'),
  ('support-client', 'Support client', '🎧'),
  ('rh-recrutement', 'RH / Recrutement', '👥'),
  ('finance', 'Finance', '💰'),
  ('juridique', 'Juridique', '⚖️'),
  ('productivite', 'Productivité', '⚡'),
  ('redaction', 'Rédaction', '✍️'),
  ('seo', 'SEO', '🔍'),
  ('reseaux-sociaux', 'Réseaux sociaux', '📱'),
  ('email', 'Email', '📧'),
  ('e-commerce', 'E-commerce', '🛒'),
  ('analyse-donnees', 'Analyse de données', '📊'),
  ('developpement', 'Développement', '💻'),
  ('devops', 'DevOps', '🔧'),
  ('cybersecurite', 'Cybersécurité', '🔒'),
  ('education', 'Éducation', '🎓'),
  ('sante', 'Santé', '🏥'),
  ('immobilier', 'Immobilier', '🏠'),
  ('tourisme', 'Tourisme', '✈️'),
  ('design', 'Design', '🎨'),
  ('video', 'Vidéo', '🎬'),
  ('audio-podcast', 'Audio / Podcast', '🎙️'),
  ('traduction', 'Traduction', '🌐'),
  ('recherche', 'Recherche', '🔬'),
  ('strategie', 'Stratégie', '🎯'),
  ('gestion-projet', 'Gestion de projet', '📋'),
  ('crm', 'CRM', '🤝'),
  ('automatisation', 'Automatisation', '🤖'),
  ('chatbot', 'Chatbot', '💬'),
  ('assistant-personnel', 'Assistant personnel', '🧑‍💼'),
  ('veille', 'Veille', '👁️'),
  ('analyse-concurrentielle', 'Analyse concurrentielle', '📈'),
  ('generation-leads', 'Génération de leads', '🧲'),
  ('onboarding', 'Onboarding', '🚀'),
  ('formation', 'Formation', '📚'),
  ('coaching', 'Coaching', '🏋️'),
  ('redaction-technique', 'Rédaction technique', '📝'),
  ('documentation', 'Documentation', '📄'),
  ('tests-qa', 'Tests / QA', '✅'),
  ('intelligence-business', 'Intelligence business', '💡'),
  ('supply-chain', 'Supply chain', '📦'),
  ('logistique', 'Logistique', '🚚'),
  ('restauration', 'Restauration', '🍽️'),
  ('agroalimentaire', 'Agroalimentaire', '🌾'),
  ('mode-retail', 'Mode / Retail', '👗'),
  ('sport-fitness', 'Sport / Fitness', '🏃'),
  ('gaming', 'Gaming', '🎮'),
  ('juridique-conformite', 'Conformité', '📜'),
  ('autre', 'Autre', '📁')
on conflict (slug) do update set
  name = excluded.name,
  icon = excluded.icon;
